name: Generate Snake

on:
  # Roda a cada 12 horas
  schedule:
    - cron: "0 */12 * * *" 
  
  # Roda SEMPRE que você fizer um push (commit) na main/master
  push:
    branches:
      - main
      - master
  
  # Permite rodar manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permissões necessárias para gravar o arquivo da cobra
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from (**Required**)
          github_user_name: ${{ github.repository_owner }}

          # Customização Premium Tokyo Night
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#7aa2f7&color_dots=#1a1b26,#164e63,#2ac3de,#7aa2f7,#bb9af7
          
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
